git-reset-to-parent: rework

diff --git a/.local/bin/git-reset-to-parent b/.local/bin/git-reset-to-parent
--- a/.local/bin/git-reset-to-parent
+++ b/.local/bin/git-reset-to-parent
@@ -1,7 +1,14 @@
 #!/usr/bin/env bash
 
-parent="$(git log --oneline | rg Merge | head -1 | cut -d ' ' -f4 | tr -d "'")"
-files="$(git diff "$(git merge-base --fork-point "$parent")" --name-only)"
+current_branch=$(git branch --show-current)
+parrent_branch=$(git log --oneline | rg -e "Merge .* into $current_branch" | head -1 | cut -d "'" -f2)
+
+if [ parrent_branch == "" ]; then
+    echo "No parent branch found."
+    exit 1
+fi
+
+files=$(git diff $parrent_branch --name-only)
 
 selected_files=$(echo "$files" | fzf -d "|" --cycle -i -m --reverse)
 
@@ -10,27 +17,32 @@ selected_files=$(echo "$files" | fzf -d "|" --cycle -i -m --reverse)
 #
 # set parent_file \"\$(git show $parent:{} 2>/dev/null)\"
 # if test -z \$parent_file
-    # set parent_file \"\"
+# set parent_file \"\"
 # end
 #
 # echo \"p: \$parent_file\"
 #
 # if test -f {}
 #
-    # echo  \"c: \$(cat \$parent_file)\"
-    # cat \$parent_file | git diff --no-index - {}
-# else 
+# echo  \"c: \$(cat \$parent_file)\"
+# cat \$parent_file | git diff --no-index - {}
+# else
 #
-    # echo  \"c: \$(cat \$parent_file)\"
-    # cat \$parent_file | git diff --no-index - {}
+# echo  \"c: \$(cat \$parent_file)\"
+# cat \$parent_file | git diff --no-index - {}
 # end
 # "
 
-if [ -n "$selected_files" ]; then
-    for file in $selected_files; do
-        git checkout "$parent" -- "$file"
-        # echo "Reset $file to its parent version."
-    done
-else
+if [! -n "$selected_files" ]; then
     echo "No files selected."
+    exit 0
 fi
+
+for file in $selected_files; do
+    if [ git checkout "$parent" -- "$file" ]; then
+        echo "Reset $file to its parent version."
+    else
+        echo "File not found in parent branch. Deleting file."
+        git rm --cached "$file"
+    fi
+done
