hypr-wal: updated script

diff --git a/.local/bin/hypr-wal b/.local/bin/hypr-wal
--- a/.local/bin/hypr-wal
+++ b/.local/bin/hypr-wal
@@ -1,23 +1,18 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 changeWallpaper() {
-	# Get the list of monitors
 	monitors=(
 		$(hyprctl monitors -j | jq -r '.[].name')
 	)
 
-	# Get a list of random pictures from the specified directory
 	random_pictures=(
 		$(fd ".png|.jpg|.jpeg" ~/Pictures/wallpapers/ | shuf -n ${#monitors[@]})
 	)
 
-	# Loop through each monitor and set a random wallpaper
 	for i in "${!monitors[@]}"; do
-		# Get the current monitor and random picture
 		monitor=${monitors[$i]}
 		random_picture=${random_pictures[$i]}
 
-		# Set the wallpaper for the current monitor
 		swww img -o "$monitor" "$random_picture" \
 			--transition-step 255 \
 			--transition-fps 60 \
@@ -48,20 +43,43 @@ updateKitty() {
 }
 
 updateBat() {
-	[[ ! -e "$(bat --config-dir)"/themes ]] && mkdir -p "$HOME"/.config/bat/themes
+	enabledTheme=$(rg -e "--theme=" "$HOME"/.config/bat/config | rg -v "#")
+	if [[ $(echo "$enabledTheme" | wc -w) -eq 1 ]]; then
+		[[ ! $(echo "$enabledTheme" | rg -e "--theme=\"base16-256\"") ]] &&
+			echo "Pls run following line to include 'base16-256' theme for bat" &&
+			echo "echo '--theme="base16-256"' >> $HOME/.config/bat/config"
+
+	else
+		echo "Warning multiple themes are set for bat."
+		echo "Pls run following line to uncomment unwanted themes and to include the 'base16-256' theme for bat"
+		echo "sed -i '/--theme/s/^/#/g' $HOME/.config/bat/config &&
+	        echo '--theme=\"base16-256\"' >> $HOME/.config/bat/config"
+	fi
 }
 
 updateBtop++() {
 	sed -i '/^color_theme = /c\color_theme = "TTY"' "$HOME"/.config/btop/btop.conf
 }
 
+updateWalfox() {
+	if ! command -v pywalfox &>/dev/null; then
+		echo "Pls install pywalfox via pip (fixes some errors)"
+		echo "pip install --index-url https://test.pypi.org/simple/ pywalfox==2.8.0rc1 --break-system-packages"
+		echo "pywalfox install"
+	else
+		pywalfox dark
+		pywalfox update
+	fi
+}
+
 changeWallpaper
 
 pic=$(cat "$(fd . "$HOME"/.cache/swww/ | head -1)")
 
-wal -i "$pic" --cols16 -n -q 2>/dev/null
+wal --saturate 1.0 -i "$pic" --cols16 -n -q 2>/dev/null
 
 updateCava
 updateKitty
 updateBtop++
-#updateBat
+updateBat
+updateWalfox
